services:
  postgres:
    image: postgres:latest
    container_name: sales-postgres
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-Senha123}
      POSTGRES_DB: ${DB_NAME:-OnlineSalesDB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-OnlineSalesDB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
    name: sales-postgres-data